# Generated by Django 5.2.5 on 2025-09-05 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0002_course_enrollment_school_student_tuitionpayment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='year_level',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='year_level',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='year_level',
            field=models.CharField(max_length=8),
        ),
        migrations.AlterField(
            model_name='tuitionpayment',
            name='due_date',
            field=models.DateField(),
        ),
    ]
