# Generated by Django 5.2.5 on 2025-09-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0004_alter_enrollment_enrollment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='school_year',
            field=models.CharField(max_length=10),
        ),
    ]
