# Generated by Django 5.2.5 on 2025-09-05 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_ID', models.CharField(max_length=5)),
                ('course_name', models.CharField(max_length=4)),
                ('year_level', models.CharField(max_length=7)),
                ('teacher_name', models.CharField(max_length=100)),
                ('course_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_ID', models.CharField(max_length=5)),
                ('student_ID', models.CharField(max_length=10)),
                ('school_year', models.IntegerField()),
                ('year_level', models.CharField(max_length=7)),
                ('enrollment_status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_ID', models.CharField(max_length=5)),
                ('school_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contact_number', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_ID', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('year_level', models.CharField(max_length=7)),
                ('date_of_birth', models.DateTimeField()),
                ('parents_contact_info', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TuitionPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_ID', models.CharField(max_length=5)),
                ('student_ID', models.CharField(max_length=10)),
                ('fee_amount', models.IntegerField()),
                ('payment_status', models.IntegerField()),
                ('due_date', models.DateTimeField()),
            ],
        ),
    ]
