# Generated by Django 5.2.5 on 2025-09-08 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0003_alter_course_year_level_alter_enrollment_year_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='enrollment_status',
            field=models.CharField(max_length=10),
        ),
    ]
