# Generated by Django 5.2.5 on 2025-09-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_enrollment', '0005_alter_enrollment_school_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionpayment',
            name='payment_status',
            field=models.CharField(max_length=10),
        ),
    ]
